type: github-webhook-example
version: 0.0.1

components:
  webhookFunction:
    type: aws-lambda
    inputs:
      memory: 512
      timeout: 10
      handler: code/handler.githubFunction
  GithubWebhookAWS:
    type: github-webhook-aws
    inputs:
      function: ${webhookFunction}
      githubRepo: serverless/serverless
      githubApiToken: xxxxxxxxxxxxx
      webhookTriggers:
        - create
