type: circular-dependencies
version: 0.0.1

components:
  myLambda:
    type: aws-lambda
    inputs:
      handler: code/index.handler
      name: ${lambdaRole.name}
      memory: 512
      timeout: 60
      role:
        arn: ${lambdaRole.arn}
  lambdaRole:
    type: aws-iam-role
    inputs:
      name: ${myLambda.name}
      service: lambda.amazonaws.com
